on:
  - pull_request
  - push

name: ci-redis

jobs:
  tests:
    name: PHP ${{ matrix.php }}-redis-${{ matrix.redis }}

    env:
      extensions: curl, intl, redis
      key: cache

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

        php:
          - "7.4"

        redis:
          - "5"
          - "6"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start Redis v${{ matrix.redis }}
        uses: superchargejs/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.redis }}

      - name: Setup cache environment
        id: cache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v2.1.1
        with:
          path: ${{ steps.cache.outputs.dir }}
          key: ${{ steps.cache.outputs.key }}
          restore-keys: ${{ steps.cache.outputs.key }}

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          coverage: xdebug
          tools: composer:v2, pecl

      - name: Determine composer cache directory on Linux
        if: matrix.os == 'ubuntu-latest'
        run: echo "::set-env name=COMPOSER_CACHE_DIR::$(composer config cache-dir)"

      - name: Determine composer cache directory on Windows
        if: matrix.os == 'windows-latest'
        run: ECHO "::set-env name=COMPOSER_CACHE_DIR::~\AppData\Local\Composer"

      - name: Cache dependencies installed with composer
        uses: actions/cache@v2.1.1
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php${{ matrix.php }}-composer-${{ matrix.dependencies }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php${{ matrix.php }}-composer-${{ matrix.dependencies }}-

      - name: Install dependencies with composer php 7.4
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Run redis tests with phpunit
        run: vendor/bin/phpunit --coverage-clover=coverage.clover

      - name: Code coverage
        if: matrix.php == '7.4'
        run: |
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.clover
