on:
  - pull_request
  - push

name: ci-redis

jobs:
  tests:
    name: PHP ${{ matrix.php }}-redis-${{ matrix.redis }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

        php:
          - "7.4"

        redis:
          - "5"
          - "6"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start Redis v${{ matrix.redis }}
        uses: superchargejs/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.redis }}

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, intl, redis
          ini-values: date.timezone='UTC'
          coverage: xdebug
          tools: composer:v2, pecl

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v2.1.4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies with Composer
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Run Redis 5 tests with PhpUnit
        if: matrix.redis == '5'
        run: vendor/bin/phpunit

      - name: Run Redis 6 tests with PhpUnit and coverage
        if: matrix.redis == '6'
        run: vendor/bin/phpunit --coverage-clover=coverage.clover

      - name: Code coverage
        if: matrix.redis == '6'
        run: |
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.clover
